name: bresenham_zingl
description: Bresenham's alogrithm implementation based on Alois Zingl's implementation
version: 1.0.0
repository: https://github.com/bjartebore/bresenham_zingl

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  curve: ^1.2.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  test: ^1.16.5
  image: ^3.0.2
  import_sorter: ^4.4.2